# Change these first
owner: angelin # Your GitHub organization or username, where this repository lives
repo: BDC # The name of this repository

sites:
  - name: Facebook
    url: https://www.facebook.com/
  - name: Youtube
    url: https://www.youtube.com/
  - name: BBC
    url: https://www.bbc.com/zhongwen/trad
  - name: WSJ
    url: https://cn.wsj.com/zh-hant
  - name: FIFA
    url: https://www.fifa.com/
  - name: error
    url: http://www.example.com/space%20here.html

    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
